name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Clear Alpine Cache
        run: |
          docker-compose run --rm app sh -c "rm -rf /var/cache/apk/*"
          
      - name: Update Alpine Repositories
        run: |
          docker-compose run --rm app sh -c "echo 'https://dl-cdn.alpinelinux.org/alpine/latest-stable/main' > /etc/apk/repositories && \
                                             echo 'https://dl-cdn.alpinelinux.org/alpine/latest-stable/community' >> /etc/apk/repositories && \
                                             apk update"
                                             
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
        
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
